language: python
python:
  - 3.6
services:
- docker
script:
- make all
- mkdir test-temp
- export AZCOPY_EXECUTABLE_PATH=$(pwd)/azcopy_linux_amd64
- export TEST_SUITE_EXECUTABLE_LOCATION=$(pwd)/test-validator
- export TEST_DIRECTORY_PATH=$(pwd)/test-temp
- travis_wait python3 $(pwd)/testSuite/scripts/run.py
